"""
MatchOptimizer Agent — B5 (CS-03).

Iteratively matches available Resources to identified Needs, weighted by equity
score, using Google ADK LoopAgent (FR-013 hard constraint).

Equity score (MDR-03): vulnerability_index * 0.6 + need_severity_normalized * 0.4

Loop terminates when:
  - allocation quality delta < convergence_threshold (converged), OR
  - max_iterations reached (best-effort, NFR-REL-002)

Routing plans generated by Gemini 2.5 Flash with exponential backoff (FM-05).

FRs: FR-007, FR-008, FR-011, FR-013
Reference: docs/SYSTEM_DESIGN.md Section 1.3.B (B5), 1.3.E (CF-05, CF-07)
"""
from __future__ import annotations

import logging
import time
from dataclasses import replace
from typing import Any, AsyncGenerator, Optional

from google.adk.agents.base_agent import BaseAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.agents.loop_agent import LoopAgent
from google.adk.events import Event, EventActions

from services.relieflink_agents.models import (
    Community,
    Match,
    MatchStatus,
    Need,
    Resource,
    RoutingPlan,
    compute_equity_score,
)

logger = logging.getLogger(__name__)

CONVERGENCE_THRESHOLD = 0.01
DEFAULT_MAX_ITERATIONS = 20
GEMINI_MODEL = "gemini-2.5-flash"
ROUTING_FALLBACK = "Routing plan unavailable — dispatch manually"

# Session state keys
_RESOURCES_KEY = "optimizer_resources"
_NEEDS_KEY = "optimizer_needs"
_COMMUNITIES_KEY = "optimizer_communities"
_MATCHES_KEY = "optimizer_matches"
_QUALITY_KEY = "optimizer_quality"
_ITERATIONS_KEY = "optimizer_iterations"
_CONVERGED_KEY = "optimizer_converged"
_STOP_REASON_KEY = "optimizer_stop_reason"
_THRESHOLD_KEY = "optimizer_threshold"


def _get_routing_plan(resource: Resource, community: Community) -> Optional[RoutingPlan]:
    """
    Generate a routing plan via Gemini 2.5 Flash.
    Retries up to 3 times with exponential backoff (FM-05).
    Falls back to None on failure — caller uses ROUTING_FALLBACK string.
    """
    import os
    from google import genai as google_genai

    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        logger.warning("GOOGLE_API_KEY not set — using fallback routing plan.")
        return None

    origin = resource.location.address if resource.location else "Unknown staging area"
    destination = community.county_name or community.fips_tract
    prompt = (
        f"Generate a concise disaster relief routing instruction in one sentence. "
        f"Origin: {origin}. Destination: {destination}, FL "
        f"(population: {community.population:,}). "
        f"Include the main highway/route and estimated travel time in minutes."
    )

    delays = [1, 2, 4]
    for attempt, delay in enumerate(delays, 1):
        try:
            client = google_genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
            )
            text = (getattr(response, "text", "") or "").strip()
            if text:
                # Extract ETA in hours from response
                import re
                eta = 0.5
                mins = re.findall(r'(\d+)\s*min', text.lower())
                if mins:
                    eta = round(int(mins[0]) / 60, 1)
                return RoutingPlan(
                    origin=origin,
                    destination=destination,
                    distance_km=0.0,
                    eta_hours=eta,
                )
        except Exception as exc:
            if attempt < len(delays):
                logger.warning(
                    "Routing plan attempt %d failed (%s), retrying in %ds...", attempt, exc, delay
                )
                time.sleep(delay)
            else:
                logger.error(
                    "Routing plan generation failed after %d attempts: %s. Returning fallback.",
                    attempt, exc,
                )
    return None


def _need_type_matches_resource(need: Need, resource: Resource) -> bool:
    """Check if a need type can be fulfilled by a resource type."""
    from services.relieflink_agents.models import NeedType, ResourceType
    mapping = {
        NeedType.SUPPLIES: ResourceType.SUPPLIES,
        NeedType.SHELTER: ResourceType.SHELTER,
        NeedType.EQUIPMENT: ResourceType.EQUIPMENT,
        NeedType.MEDICAL: ResourceType.PERSONNEL,
        NeedType.EVACUATION: ResourceType.EQUIPMENT,
    }
    return mapping.get(need.need_type) == resource.type


class _ScoringAgent(BaseAgent):
    """
    ADK BaseAgent sub-agent for LoopAgent.
    Each invocation: selects the highest equity-score unmatched resource-need pair,
    creates a Match, updates resource/need quantities, and escalates when done.
    """

    model_config = {"arbitrary_types_allowed": True}

    def __init__(self, **kwargs):
        super().__init__(name="ScoringAgent", **kwargs)

    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        state = ctx.session.state
        resources: list[Resource] = state.get(_RESOURCES_KEY, [])
        needs: list[Need] = state.get(_NEEDS_KEY, [])
        communities: dict[str, Community] = state.get(_COMMUNITIES_KEY, {})
        matches: list[Match] = state.get(_MATCHES_KEY, [])
        prev_quality: Optional[float] = state.get(_QUALITY_KEY)
        threshold: float = state.get(_THRESHOLD_KEY, CONVERGENCE_THRESHOLD)

        # Find best resource-need pair by equity score
        best: Optional[tuple[float, Resource, Need, Community]] = None
        for resource in resources:
            if resource.quantity <= 0:
                continue
            for need in needs:
                if need.quantity_needed <= 0:
                    continue
                if not _need_type_matches_resource(need, resource):
                    continue
                community = communities.get(need.community_fips_tract)
                if community is None:
                    continue
                score = compute_equity_score(
                    vulnerability_index=community.vulnerability_index,
                    need_severity=need.severity,
                )
                if best is None or score > best[0]:
                    best = (score, resource, need, community)

        if best is None:
            state[_STOP_REASON_KEY] = "no_remaining_pairs"
            state[_CONVERGED_KEY] = True
            yield Event(author=self.name, actions=EventActions(escalate=True))
            return

        equity_score, resource, need, community = best
        quantity_allocated = min(resource.quantity, need.quantity_needed)
        resource.quantity -= quantity_allocated
        need.quantity_needed -= quantity_allocated

        routing = _get_routing_plan(resource, community)
        match = Match(
            resource_id=resource.resource_id,
            need_id=need.need_id,
            equity_score=equity_score,
            routing_plan=routing,
            status=MatchStatus.RECOMMENDED,
        )
        matches.append(match)

        current_quality = sum(m.equity_score for m in matches) / len(matches)
        state[_QUALITY_KEY] = current_quality
        state[_MATCHES_KEY] = matches
        state[_ITERATIONS_KEY] = state.get(_ITERATIONS_KEY, 0) + 1

        # Convergence check
        if prev_quality is not None and abs(prev_quality - current_quality) < threshold:
            state[_CONVERGED_KEY] = True
            state[_STOP_REASON_KEY] = "quality_plateau"
            yield Event(author=self.name, actions=EventActions(escalate=True))
            return

        yield Event(author=self.name)


class MatchOptimizerAgent(BaseAgent):
    """
    B5 — MatchOptimizer ADK Agent.

    Wraps a real google.adk LoopAgent containing _ScoringAgent.
    Reads resource_data + needs_data from session state (written by CS-02 agents).
    Writes match_data to session state for B7 Backend API.

    CF-05 output written to session state under key "match_data":
      { "matches": [...], "iterations_run": int, "converged": bool,
        "total_equity_score": float }
    """

    model_config = {"arbitrary_types_allowed": True}

    def __init__(
        self,
        max_iterations: int = DEFAULT_MAX_ITERATIONS,
        convergence_threshold: float = CONVERGENCE_THRESHOLD,
        **kwargs,
    ):
        super().__init__(name="MatchOptimizerAgent", **kwargs)
        self._max_iterations = max_iterations
        self._convergence_threshold = convergence_threshold

    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        # Load inputs from session state (written by ResourceScannerAgent + NeedMapperAgent)
        resource_data = ctx.session.state.get("resource_data", {})
        needs_data = ctx.session.state.get("needs_data", {})

        raw_resources = resource_data.get("resources", [])
        raw_needs = needs_data.get("needs", [])
        raw_communities = needs_data.get("communities", [])

        resources = _dicts_to_resources(raw_resources)
        needs = _dicts_to_needs(raw_needs)
        communities = {c.fips_tract: c for c in _dicts_to_communities(raw_communities)}

        # Initialise shared loop state
        ctx.session.state[_RESOURCES_KEY] = resources
        ctx.session.state[_NEEDS_KEY] = needs
        ctx.session.state[_COMMUNITIES_KEY] = communities
        ctx.session.state[_MATCHES_KEY] = []
        ctx.session.state[_QUALITY_KEY] = None
        ctx.session.state[_ITERATIONS_KEY] = 0
        ctx.session.state[_CONVERGED_KEY] = False
        ctx.session.state[_STOP_REASON_KEY] = None
        ctx.session.state[_THRESHOLD_KEY] = self._convergence_threshold

        # Run real ADK LoopAgent (FR-013)
        loop = LoopAgent(
            name="MatchOptimizationLoop",
            sub_agents=[_ScoringAgent()],
            max_iterations=self._max_iterations,
        )
        async for event in loop.run_async(ctx):
            yield event

        # Extract results and check if max_iterations was hit without convergence
        matches = ctx.session.state.get(_MATCHES_KEY, [])
        iterations_run = ctx.session.state.get(_ITERATIONS_KEY, 0)
        converged = ctx.session.state.get(_CONVERGED_KEY, False)

        if iterations_run >= self._max_iterations and not converged:
            logger.warning(
                "MatchOptimizer reached max_iterations=%d without convergence. "
                "Returning best-effort allocation. (FM-04)",
                self._max_iterations,
            )
            # Set convergence_note on all matches (FM-04 / NFR-REL-002)
            matches = [
                replace(m, convergence_note="Best-effort allocation. Optimization did not fully converge.")
                for m in matches
            ]
            ctx.session.state[_MATCHES_KEY] = matches

        total_equity = sum(m.equity_score for m in matches)

        # CF-05 output contract
        ctx.session.state["match_data"] = {
            "matches": [_match_to_dict(m) for m in matches],
            "iterations_run": iterations_run,
            "converged": converged,
            "total_equity_score": round(total_equity, 4),
        }

        logger.info(
            "MatchOptimizerAgent: completed. matches=%d iterations=%d converged=%s total_equity=%.4f",
            len(matches), iterations_run, converged, total_equity,
        )

    def optimize_from_data(
        self,
        resources: list[Resource],
        needs: list[Need],
        communities: list[Community],
    ) -> dict[str, Any]:
        """
        Standalone entry point for direct usage and testing.
        Uses real ADK InvocationContext + InMemorySessionService.
        Returns CF-05 compliant dict.
        """
        import asyncio
        import uuid
        from google.adk.agents.invocation_context import InvocationContext
        from google.adk.sessions.in_memory_session_service import InMemorySessionService

        svc = InMemorySessionService()

        async def _run():
            session = await svc.create_session(app_name="relieflink", user_id="optimizer")
            session.state["resource_data"] = {
                "resources": [_resource_to_dict(r) for r in resources],
            }
            session.state["needs_data"] = {
                "needs": [_need_to_dict(n) for n in needs],
                "communities": [_community_to_dict(c) for c in communities],
            }
            ctx = InvocationContext(
                session_service=svc,
                invocation_id=str(uuid.uuid4()),
                agent=self,
                session=session,
            )
            async for _ in self._run_async_impl(ctx):
                pass
            return ctx.session.state.get("match_data", {
                "matches": [], "iterations_run": 0, "converged": False, "total_equity_score": 0.0
            })

        return asyncio.run(_run())

    def reoptimize(
        self,
        resources: list[Resource],
        needs: list[Need],
        communities: list[Community],
        accepted_match_ids: list[str],
        skipped_match_ids: list[str],
        previous_matches: list[Match],
    ) -> dict[str, Any]:
        """
        Re-run optimization after operator accept/skip decisions (FR-011 / CF-07).
        Accepted matches lock resources/needs; skipped matches release them.
        Returns CF-05 compliant dict of fresh pending matches.
        """
        accepted = set(accepted_match_ids)
        skipped = set(skipped_match_ids)

        resource_pool = {r.resource_id: replace(r) for r in resources}
        need_pool = {n.need_id: replace(n) for n in needs}

        for match in previous_matches:
            if match.match_id in accepted:
                resource_pool[match.resource_id].quantity = 0
                need_pool[match.need_id].quantity_needed = 0
            # skipped matches: resources/needs stay available

        remaining_resources = [r for r in resource_pool.values() if r.quantity > 0]
        remaining_needs = [n for n in need_pool.values() if n.quantity_needed > 0]

        return self.optimize_from_data(remaining_resources, remaining_needs, communities)


# ---------------------------------------------------------------------------
# Dict ↔ Model conversion helpers (session state uses dicts, not dataclasses)
# ---------------------------------------------------------------------------

def _dicts_to_resources(raw: list[dict]) -> list[Resource]:
    from services.relieflink_agents.models import Location, ResourceType, ResourceStatus
    result = []
    for r in raw:
        try:
            loc_raw = r.get("location") or {}
            location = Location(
                lat=float(loc_raw.get("lat", 0.0)),
                lon=float(loc_raw.get("lon", 0.0)),
                address=loc_raw.get("address", ""),
                fips_code=loc_raw.get("fips_code", ""),
            ) if loc_raw else None
            result.append(Resource(
                resource_id=r.get("resource_id", ""),
                type=ResourceType(r.get("type", "supplies")),
                subtype=r.get("subtype", ""),
                quantity=int(r.get("quantity", 0)),
                location=location,
                owner_agency_id=r.get("owner_agency_id", ""),
                status=ResourceStatus(r.get("status", "available")),
            ))
        except (ValueError, KeyError):
            continue
    return result


def _dicts_to_needs(raw: list[dict]) -> list[Need]:
    from services.relieflink_agents.models import NeedType
    result = []
    for n in raw:
        try:
            result.append(Need(
                need_id=n.get("need_id", ""),
                community_fips_tract=n.get("community_fips_tract", ""),
                need_type=NeedType(n.get("need_type", "supplies")),
                severity=float(n.get("severity", 0.0)),
                quantity_needed=int(n.get("quantity_needed", 0)),
                quantity_fulfilled=int(n.get("quantity_fulfilled", 0)),
                equity_score=float(n.get("equity_score", 0.0)),
            ))
        except (ValueError, KeyError):
            continue
    return result


def _dicts_to_communities(raw: list[dict]) -> list[Community]:
    from services.relieflink_agents.models import SVIThemes
    result = []
    for c in raw:
        try:
            themes_raw = c.get("svi_themes") or {}
            svi_themes = SVIThemes(
                socioeconomic=float(themes_raw.get("socioeconomic", 0.5)),
                household=float(themes_raw.get("household", 0.5)),
                minority=float(themes_raw.get("minority", 0.5)),
                housing_transport=float(themes_raw.get("housing_transport", 0.5)),
            ) if themes_raw else None
            result.append(Community(
                fips_tract=c.get("fips_tract", ""),
                county_fips=c.get("county_fips", ""),
                state=c.get("state", "FL"),
                population=int(c.get("population", 0)),
                vulnerability_index=float(c.get("vulnerability_index", 0.5)),
                svi_themes=svi_themes,
                county_name=c.get("county_name", ""),
            ))
        except (ValueError, KeyError):
            continue
    return result


def _match_to_dict(m: Match) -> dict:
    routing = None
    if m.routing_plan:
        routing = {
            "origin": m.routing_plan.origin,
            "destination": m.routing_plan.destination,
            "distance_km": m.routing_plan.distance_km,
            "eta_hours": m.routing_plan.eta_hours,
        }
    return {
        "match_id": m.match_id,
        "resource_id": m.resource_id,
        "need_id": m.need_id,
        "equity_score": m.equity_score,
        "routing_plan": routing,
        "status": m.status.value,
        "convergence_note": m.convergence_note,
    }


def _resource_to_dict(r: Resource) -> dict:
    return {
        "resource_id": r.resource_id,
        "type": r.type.value,
        "subtype": r.subtype,
        "quantity": r.quantity,
        "location": {
            "lat": r.location.lat, "lon": r.location.lon,
            "address": r.location.address, "fips_code": r.location.fips_code,
        } if r.location else None,
        "owner_agency_id": r.owner_agency_id,
        "status": r.status.value,
    }


def _need_to_dict(n: Need) -> dict:
    return {
        "need_id": n.need_id,
        "community_fips_tract": n.community_fips_tract,
        "need_type": n.need_type.value,
        "severity": n.severity,
        "quantity_needed": n.quantity_needed,
        "quantity_fulfilled": n.quantity_fulfilled,
        "equity_score": n.equity_score,
    }


def _community_to_dict(c: Community) -> dict:
    return {
        "fips_tract": c.fips_tract,
        "county_fips": c.county_fips,
        "state": c.state,
        "population": c.population,
        "vulnerability_index": c.vulnerability_index,
        "county_name": c.county_name,
        "svi_themes": {
            "socioeconomic": c.svi_themes.socioeconomic,
            "household": c.svi_themes.household,
            "minority": c.svi_themes.minority,
            "housing_transport": c.svi_themes.housing_transport,
        } if c.svi_themes else None,
    }
